# config.toml
theme = "darcula-solid"

[editor]
line-number = "relative"
mouse = false
auto-completion = true
auto-format = true
auto-pairs = true
rulers = [80, 120]
cursorline = true
color-modes = true
end-of-line-diagnostics = "hint"
# bufferline = "always"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "primary-selection-length", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
"ret" = ["open_below", "normal_mode"]
# Move line up/down using A-k, A-j
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
A-left = "goto_previous_buffer"
A-right = "goto_next_buffer"
A-o = ":config-open"
A-r = ":config-reload"
A-f = ":format"

[keys.normal.left]
d = "goto_prev_diag"
f = "goto_prev_function"
t = "goto_prev_class"
a = "goto_prev_parameter"
c = "goto_prev_comment"
T = "goto_prev_test"
p = "goto_prev_paragraph"
g = "goto_prev_change"

[keys.normal.right]
d = "goto_next_diag"
f = "goto_next_function"
t = "goto_next_class"
a = "goto_next_parameter"
c = "goto_next_comment"
T = "goto_next_test"
p = "goto_next_paragraph"
g = "goto_next_change"

[keys.normal.up]
D = "goto_first_diag"
G = "goto_first_change"
space = "add_newline_above"

[keys.normal.down]
D = "goto_last_diag"
G = "goto_last_change"
space = "add_newline_below"
