
[[language]]
name = "rust"
file-types = ["rs"]
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "typst"
auto-format = false # typstfmt can break things sometimes
formatter = { command = "typstfmt" args = ["--output", "-"] }
